# Generated by Django 3.2.4 on 2021-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256, verbose_name='customer name')),
                ('customer_city', models.CharField(max_length=256, verbose_name='customer city')),
                ('customer_country', models.CharField(max_length=256, verbose_name='customer country')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('products', models.ManyToManyField(related_name='orders', to='products.Product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
